apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ttm-as-a-service
spec:
  replicas: 1
  test: false
  selector:
    deploymentconfig: ttm-as-a-service
    app.kubernetes.io/name: thoth
    app.kubernetes.io/component: ttm-as-a-service
    app.kubernetes.io/managed-by: aicoe-thoth-devops
  template:
    metadata:
      labels:
        deploymentconfig: ttm-as-a-service
        app.kubernetes.io/name: thoth
        app.kubernetes.io/component: ttm-as-a-service
        app.kubernetes.io/managed-by: aicoe-thoth-devops
    spec:
      containers:
        - name: ttm-as-a-service
          image: ttm-as-a-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: APP_FILE
              value: wsgi.py
            - name: APP_CONFIG
              value: "gunicorn.conf.py"
            - name: PORT
              value: "5000"
            - name: GITHUBAPP_ID
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_ID
                  name: githubapp-id
            - name: GITHUBAPP_SECRET
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_SECRET
                  name: githubapp-secret
            - name: GITHUBAPP_KEY
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_KEY
                  name: githubapp-key
      restartPolicy: Always
